# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MJ Kim
email: min7859@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love working with data in all forms, structured and unstructured,
  and am deeply interested in solving everyday problems with code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mj.kim" # the base hostname & protocol for your site
twitter_username: mjane0111
github_username: mj111

# Build settings
markdown: kramdown
